# Generated by Django 2.2.6 on 2019-10-07 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("django_mailbox", "0008_auto_20191007_1024"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserMailbox",
            fields=[
                (
                    "mailbox",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="user",
                        serialize=False,
                        to="django_mailbox.Mailbox",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mailboxes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Mailbox",
                "verbose_name_plural": "User Mailboxes",
                "ordering": ("user",),
            },
        )
    ]
